### ISSUE TITLE
cant use with @hyperapp/router

### ISSUE THREAD

**Issue by zdhxiong** [hyperapp/transitions#10] opened 2018-04-12 09:49 UTC
when i use with @hyperapp/router, there is no animation, and it shows ”[object Object]“
![ezgif-4-f631d14222](https://user-images.githubusercontent.com/3030330/38669801-bd29552c-3e79-11e8-8aa8-b14a59232fee.gif)

it's my code:
```js
import {h, app} from "hyperapp" // 1.2.5
import {Link, Route, location} from "@hyperapp/router" // 0.7.0
import {Enter, Exit} from "@hyperapp/transitions" // 1.0.2

const Home = () =>
    <Enter css={{opacity: "0"}}>
        <Exit css={{opacity: "0", transform: "scale(2.0,2.0)"}}>
            <h2>Home</h2>
        </Exit>
    </Enter>

const About = () =>
    <Enter css={{opacity: "0"}}>
        <Exit css={{opacity: "0", transform: "scale(2.0,2.0)"}}>
            <h2>About</h2>
        </Exit>
    </Enter>

const state = {
    location: location.state
};

const actions = {
    location: location.actions
};

const view = state => (
    <div>
        <Link to="/">Home</Link>
        <Link to="/about">About</Link>

        <hr/>

        <Route path="/" render={Home}/>
        <Route path="/about" render={About}/>
    </div>
);

const main = app(state, actions, view, document.body)

const unsubscribe = location.subscribe(main.location)
```

**Comment by zaceno** [comment] 2018-04-12 10:46
Ok one not obvious problem with using the router and transitions together is that while hyperapp components generally can return an array of children, the component you pass to `render={SomeComponent}` *can not*. It *must* be a virtual node.

The transition components do not return virtual nodes, because they are only *decorators* meaning they modify and return their children. So what your `Home` component is returning, is actually an *array* that looks like:

```
[ 
  {
    tagName: 'h2',
    attributes: {
      oncreate: //set by Enter transition,
      onupdate: //set by Exit transiition,
      onremove: //set by Exit transition,
     },
    children: [
      'Home'
    ]
  }
]
```

... which the `render` prop of `Route` can't deal with.

One option is to wrap the components in a non-transitioned, top level `div` like:

```
const Home = () =>
    <div>
    <Enter css={{opacity: "0"}}>
        <Exit css={{opacity: "0", transform: "scale(2.0,2.0)"}}>
            <h2>Home</h2>
        </Exit>
    </Enter>
   </div>
```

Now your `Home` component will return a single virtual-dom node, rather than an array of them, which makes `render` happy

**Comment by zdhxiong** [comment] 2018-04-12 11:07
I wrap components in `div`, now Enter animation can show, but Exit animation can't show.
because when i click a link, the component is removed immediately. what should i do?

**Comment by zaceno** [comment] 2018-04-12 12:11
Hm... that's strange. Enter works but Exit doesn't? That might be a bug. I'll have to look into that later tonight when I'm at home and have some time to reproduce and investigate.

**Comment by zaceno** [comment] 2018-04-12 12:13
In the mean time, just for some added info: what browser are you using to test this?

**Comment by zaceno** [comment] 2018-04-12 12:15
By the way: Props on the very well written bug report. You included your full code and a gif to show the problem. That's 💯

**Comment by zaceno** [comment] 2018-04-12 22:40
@zdhxiong Since this isn’t something I can fix in this repo, and you have the workaround above (key the top node of a routed component) I’m going to close this issue. 

Sorry my explanation wasn’t great... Maybe I should document this, but I’m going to wait and see what happens with the router issue I opened (linked above) - I don’t want to instruct people to use a workaround for what might be a bug :)

**Closed by zaceno** 2018-04-12 22:40 UTC

**Comment by zdhxiong** [comment] 2018-04-13 01:24
This perfectly solved my problem, thank you for your answer.
